### ISSUE TITLE
[New New UI] Feature Request: undo Reddit's `display: inline` and add fading effect on text post preview

### ISSUE THREAD

**Issue by bmndc** [joelacus/RedditEnhancer#121]
Doing this later.

![](https://github.com/user-attachments/assets/c367ada2-153b-4200-8966-0c737fdf87ed)

```css
div.md.feed-card-text-preview > p, 
div.md.feed-card-text-preview > p ~ object,
div.md.feed-card-text-preview > pre {
    display: block !important;
    margin: 0 0 .75rem 0 !important;
    overflow: inherit;
}
div.md.feed-card-text-preview p > strong {
    font-weight: 700;
}
div.md.feed-card-text-preview p > em {
    font-style: italic;
}
div.md.feed-card-text-preview {
    max-height: 250px;
    mask-image: linear-gradient(180deg, #000 150px, transparent);
}
```

TODO:
- [ ] Add a slider to adjust the maximum height of the text post preview
- [ ] Add a slider to adjust when the text starts to fade
