### ISSUE TITLE
[BUG] New New UI: Reddit introduced the collapsible side menu, which renders many features not working

### ISSUE THREAD

**Issue by bmndc** [joelacus/RedditEnhancer#138]
Fortunately Resize Feed/Post seems to not be affected. I'll work on this ASAP.

* Side Menu Width is completely broken (remind me not to always rely on Reddit's CSS variables)
* Hide the Side Menu still works, but the padding left by the hidden side menu still remains, limiting the width available for Resize Feed/Post
* Possibly renaming Side Menu Toggle Button to *Classic Collapsible Side Menu*?
* Side Menu Icons Only seems to conflict with Compact Sub Rule List
* Change auto to 1fr in Resize Feed/Post, as auto seems to cause weird behaviour in Chrome

**Comment by joelacus** [comment]
Oh ok, thank you catching this. I haven't noticed any change on Reddit yet. Probably A/B testing again.

**Comment by bmndc** [comment]
@joelacus uncollapsed:

![](https://github.com/user-attachments/assets/3f4c83a7-132b-4f3f-a61f-bed6a9f9c480)

collapsed:

![](https://github.com/user-attachments/assets/706f146f-8c98-42ad-b333-4807dd1e7199)

when hovering over the exposed part of the collapsed side menu:

![](https://github.com/user-attachments/assets/9412d12c-b6d4-4e2f-a708-f93f2a613f3f)

**Comment by bmndc** [comment]
the new structure now is:

1. `<div class="grid-container theme-rpl grid flex-nav-collapsed">` 
2. `<flex-left-nav-container id="left-sidebar-container" class="left-sidebar theme-rpl isolate order-first hidden m:block border-0 border-solid s:border-r-sm border-r-neutral-border" expanded="0" parent-grid-selector=".grid-container">`
    * `<div class="hoverable-target">` in shadow DOM, hovering on it adds the `hovered` CSS class
4. `<div id="flex-left-nav-container">`
5. `<div id="flex-nav-buttons">` + `<div id="flex-left-nav-contents" hidden="">`
6. `<reddit-sidebar-nav id="left-sidebar"...>`

```css
@media (min-width: 1200px) {
  .grid-container:not(.grid-full).flex-nav-collapsed {
    --flex-nav-width: 32px;
  }
  .grid-container:not(.grid-full).flex-nav-expanded {
    --flex-nav-width: 272px;
  }
}
flex-left-nav-container {
  --hover-curve: var(--expand-curve, cubic-bezier(0.65, 0, 0.35, 1));
  --unhover-curve: var(--collapse-curve, cubic-bezier(0.87, 0, 0.13, 1));
  --hover-duration: var(--expand-duration, 300ms);
  --unhover-duration: var(--collapse-duraction, 250ms);
  --flex-nav-closed-size: 32px;
  --flex-nav-expanded-size: 272px;
  --closed-floating-translation: calc(var(--flex-nav-expanded-size) * -1 + (var(--flex-nav-closed-size)));
  --open-floating-translation: 0%;
  --left-nav-box-shadow-none: 0 0 0 rgba(0, 0, 0, 0);
  --left-nav-box-shadow-hover: var(--elevation-lg);
  --left-nav-min-height: calc(100vh - var(--shreddit-header-height));
  --flex-nav-z-index: 100;
  z-index: 1;
  contain: size,layout;
  position: relative;
  box-sizing: border-box;
  border-right: none !important;
  min-height: var(--left-nav-min-height);
}
flex-left-nav-container[expanded="0"] #flex-left-nav-container {
  transform: translateX(var(--closed-floating-translation));
}
flex-left-nav-container[expanded="1"].hovered #flex-left-nav-container,
flex-left-nav-container[expanded="0"] #flex-left-nav-container {
  display: block;
  z-index: var(--flex-nav-z-index);
  visibility: visible;
  opacity: 1;
  transform: translate(var(--open-floating-translation));
  transition: none;
}
flex-left-nav-container #flex-left-nav-container {
  contain: layout;
  box-sizing: border-box;
  will-change: transform,box-shadow,border-right;
  position: fixed;
  width: var(--flex-nav-expanded-size);
  border-right: 1px solid var(--color-neutral-border);
  background-color: var(--color-neutral-background);
  box-shadow: var(--left-nav-box-shadow-none);
  min-height: var(--left-nav-min-height);
}
flex-left-nav-container #flex-nav-buttons {
  position: absolute;
  top: 20px;
  z-index: calc(var(--flex-nav-z-index) + 1);
  right: -16px;
}
flex-left-nav-container #flex-left-nav-contents {
  will-change: opacity;
  box-sizing: border-box;
  opacity: 0;
  transition: opacity var(--unhover-duration) var(--unhover-curve);
}
flex-left-nav-container[expanded="1"] #flex-left-nav-contents {
  opacity: 1;
  transition: opacity var(--hover-duration) var(--hover-curve);
}
flex-left-nav-container reddit-sidebar-nav#left-sidebar {
  padding-right: 1.5rem;
}
```

when opening the side panel:

* `flex-nav-collapsed` changes to `flex-nav-expanded`
* `expanded` set to 1
* `hidden` attribute of `#flex-left-nav-contents` removed
* a session cookie, `hui_flex_nav_expanded_state` changes from 0 to 1
